### ISSUE TITLE
How to remove Trow?

### ISSUE THREAD

**Issue by arnoudbevers** [ContainerSolutions/trow#102]
Hi, I was wondering if it's possible to remove/uninstall trow from a cluster, and if so - how? I am having problems with some configuration and need to uninstall Trow to proceed. Thanks!

**Comment by amouat** [comment]
How did you install trow? If you used the standard install it should be straightforward, just run `kubectl delete -k <my_config>` where `<my_config>` is your kustomize overlay directory e.g. `kubectl delete -k overlays/mycluster` .

If you used the quick install, I'll need to have a quick check but it should be simple as well.

**Comment by arnoudbevers** [comment]
I have deleted it, but when reinstalling it gets stuck on the 'Approving certificate' step.. Executing the command manually gives a 'No resources found' error, but it happens after waiting a bit as well.

![afbeelding](https://user-images.githubusercontent.com/23448156/80484571-3a82cf00-8958-11ea-82f3-ec015983cd97.png)

I have cert-manager running in the `cert-manager` workspace, and a self-signed Issuer in the same workspace. Would you know how to fix it?

**Comment by amouat** [comment]
Right, so this is on the quick install.

If you have cert-manager running, I'd strongly suggest using the standard install instead and configuring Trow to use cert-manager. There is an overlay [available here](https://github.com/ContainerSolutions/trow/tree/master/install/overlays/cert-manager-nginx) that should be 99% of what you need. This is a much better - more stable and less hacky - way to install trow.

Regarding the exact error, I think things can get confused with the k8s CA and CSRs - Trow picks up the previously assigned cert when it shouldn't. I'd have to look into the details to be honest. I don't *think* it has anything to do with cert-manager.

I'll try to recreate the problem locally and come up with a solution, but the best answer really is to use the standard install.

**Comment by amouat** [comment]
Regarding the original question, I'll add a section to the docs on uninstall - I should have had this already.

**Comment by amouat** [comment]
I've added uninstall instructions. I also tested running the install script again after uninstall - this worked fine, but it did pick up the previous certficate. So there's another issue there, but I'm not sure what it is.

I'm going to close this issue for the minute, but please open a new issue if you hit cert issues again, and especially if you're able to recreate the problem.

**Comment by encanto-oss** [comment]
Where is the uninstall instructions?

**Comment by amouat** [comment]
@encanto-oss Under the heading "Uninstall Instructions" in the quick-start and kustomize instructions.
