### ISSUE TITLE
running on AWS: copy-certs issue and not able to start images.

### ISSUE THREAD

**Issue by mariotti** [ContainerSolutions/trow#12]
I just run the default install.sh on a cluster created on AWS using the "demo" of kubeone.
(https://github.com/kubermatic/kubeone/blob/master/docs/quickstart-aws.md)

On the command line all looks fine, this is a reconfiguration:

> Copying certs to nodes
> job.batch "copy-certs-256f98ff-dd72-11e9-bf2c-06bc88d2476e" deleted
> job.batch "copy-certs-6cf026f4-dd71-11e9-a174-0251f5d573ce" deleted
> job.batch "copy-certs-8e37e875-dd71-11e9-a174-0251f5d573ce" deleted
> job.batch "copy-certs-b5e8b90c-dd71-11e9-bf2c-06bc88d2476e" deleted
> job.batch/copy-certs-b5e8b90c-dd71-11e9-bf2c-06bc88d2476e created
> job.batch/copy-certs-6cf026f4-dd71-11e9-a174-0251f5d573ce created
> job.batch/copy-certs-256f98ff-dd72-11e9-bf2c-06bc88d2476e created
> job.batch/copy-certs-8e37e875-dd71-11e9-a174-0251f5d573ce created
> 

I get:

> 0/4 nodes are available: 4 node(s) didn't match node selector.

> 0/4 nodes are available: 1 node(s) had taints that the pod didn't tolerate, 3 node(s) didn't match node selector.

In kube-public space under jobs.

In the default name space I see:

> Failed to pull image "trow.kube-public:31000/test/nginx:alpine": rpc error: code = Unknown desc = Error response from daemon: Get https://trow.kube-public:31000/v2/: dial tcp: lookup trow.kube-public: no such host

But the deployment is there.

I have relatively good experience with AWS but honestly pretty close to zero with k8s.

The kubeone setup seems pretty ok as I can run the dashboard (where I got the error messages) and it seems to run the coredns.

How can I get more logs to debug this issue?

**Comment by amouat** [comment]
Interesting. All the testing I've done so far has been one Google and locally, I'll have a look at AWS. You're running on an EC2 right? Do you know which version of k8s you installed?

**Comment by amouat** [comment]
This is a bit bizarre. It seems the nodeSelector isn't matching the node's hostname. I don't understand it.

I've found a bug in the script where it's attempting to schedule the job on the masters, which doesn't need to happen, but that's not causing the problem.

If you want to get Trow going, run:

```
kubectl get nodes -o go-template-file --template copy-certs-tmpl.yaml > /tmp/yaml
```

Delete all but one of the jobs and remove the nodeSelector line. You may also want to rename the job.

**Comment by amouat** [comment]
Got it - I was using the wrong field. Should be an easy fix.

**Comment by amouat** [comment]
So, I've fixed this problem but not the scheduling on masters one. I'll do a full test once I've figured that one out and close this issue if it all works.

In the meantime if you use the scripts in master it should work.

**Comment by amouat** [comment]
This should all be fixed in https://github.com/ContainerSolutions/trow/commit/579268b0d12e4fa1d769a2537aed1e282a37e90b.

Tested with the current version of the kubeone installer. Note that you will need to open inbound port 31000 to push any images.

Please let me know how you get on!
