### ISSUE TITLE
CNCF-Runtime discussion/presentation(?)

### ISSUE THREAD

**Issue by raravena80** [ContainerSolutions/trow#135]
Hello Trow team,

I'm one of the co-chairs of the CNCF SIG-Runtime, I was looking at your project and I think it would be great for you to present/discuss it at one of our meetings. For example, discuss things such as how is Trow different from [Harbor](https://goharbor.io/) and [Quay](https://quay.io/). I think the community would greatly benefit.

Let me know if this something you'd be interested in doing. If yes, please feel free to add it to our [agenda](https://bit.ly/cncf-sig-runtime-meeting-notes) or reach out to me (raravena80 at gmail.com)

Thanks!

**Comment by amouat** [comment]
Thanks for getting in touch!

We're definitely interested in doing this. I need to put together some materials on Trow and its goal first (which we need anyway) and then I'll get back to you.

**Comment by raravena80** [comment]
Hi, @amouat just checking if you are interested in presenting/discuss the project in our next meeting on Nov 5th? Thanks!

**Comment by amouat** [comment]
Hi,

Sorry for not getting back to you before @raravena80. Let's schedule a date so I can't put it off :) We're definitely very keen to do this.

I could potentially do a Nov 5th, but it's a little tight as I'm on holiday before and flat out this week. Would it be possible to do Dec 3rd, or do you try to only have a single presentation?

My e-mail is adrian.mouat at container-solutions.com if you'd like to discuss over e-mail.

**Comment by amouat** [comment]
Yes, Dec 17th sounds great!

**Comment by amouat** [comment]
I'll follow up on e-mail to check where we are with this.

**Comment by amouat** [comment]
Done! There is a recording: https://youtu.be/4-5ncFgZiEM?t=294
