### ISSUE TITLE
Support Containerd 1.3.0 and microk8s

### ISSUE THREAD

**Issue by amouat** [ContainerSolutions/trow#14]
Kubernetes is moving away from docker and to the containerd as the default runtime. This has implications for how we configure Trow. If we are lucky, it maybe be possible to use a combination of the mirror and TLS settings in containerd to configure Trow in secure mode with no need for the `/etc/hosts` hack on the nodes.

Microk8s has already moved to containerd and is an ideal target platform for trying out Trow. However, at the time of writing microk8s uses containerd 1.2.5, which lacks required config. When mcirok8s moves to 1.3.0 we should try again.

**Comment by amouat** [comment]
https://github.com/ubuntu/microk8s/issues/702

**Comment by amouat** [comment]
Containerd 1.3 is now on edge (`snap install microk8s --classic --channel=edge`)

**Comment by ianmiell** [comment]
Installed from edge as per above, but containerd still appears to be 1.2.5:

```
root@ubuntu-disco:~# /snap/microk8s/1139/bin/containerd --version
containerd github.com/containerd/containerd v1.2.5 bb71b10fd8f58240ca47fbb579b9d1028eea7c84
```

**Comment by ianmiell** [comment]
It looks like the above command doesn't install containerd 1.3 AFAICT.

I also tried: 

```
snap refresh microk8s --classic --channel=1.18/edge
```

(the latest version available), but that also seems to use 1.2.5.

**Comment by ianmiell** [comment]
Looks like 1.3 was reverted for the time being:

https://github.com/ubuntu/microk8s/pull/813

**Comment by ianmiell** [comment]
This is parked until 1.3 comes with containerd.

At that point we can try containerd without the /etc/hosts hack and see if that works.

**Comment by ianmiell** [comment]
Scratch the above; it was the version of ubuntu that microk8s w/containerd 1.3+ did not like.

I have 1.3.2 working against microk8s.

Unfortunately, both of these configs failed to work after:

- Taking comment out of /etc/hosts

- Making changes to containerd-template.toml (see below 1)

- Restarting containerd

1 - Changes to containerd-template.toml tried

```
        [plugins.cri.registry.mirrors."127.0.0.1:31000"]
          endpoint = ["https://trow.kube-public:31000"]
```

```
        [plugins.cri.registry.mirrors."trow.kube-public:31000"]
          endpoint = ["https://127.0.0.1:31000"]
```

Both resulted in:

```
root@trow1:/var/snap/microk8s/x1/args# docker push trow.kube-public:31000/nginx
The push refers to repository [trow.kube-public:31000/nginx]
Get https://trow.kube-public:31000/v2/: dial tcp: lookup trow.kube-public: no such host
```

**Comment by amouat** [comment]
Closing in favour #78
