### ISSUE TITLE
unable to deploy local image

### ISSUE THREAD

**Issue by CreepDth** [ContainerSolutions/trow#140]
After we pushed an image remotely for testing, I am now unable to deploy it into k8.
The message that I get in the Replication Sets Overview is:

_Error creating: admission webhook "validator.trow.io" denied the request: Remote image hello-world-remco:test1 disallowed as not contained in this registry and not in allow list_

According to your docs its similar to https://github.com/ContainerSolutions/trow/blob/master/docs/USER_GUIDE.md#my-pod-cant-pull-images-from-trow

But I am unable to find out what I need to change to make this work.
Greetz,
Remco

**Comment by CreepDth** [comment]
Ok lets close this ticket; I found out the issue. 
The example given here: $ kubectl run trow-test --image=trow.kube-public:31000/myimage:mytag is replaced for kubectl create deployment and I forgot to add : trow.kube-public:31000/ so I used  --image=hello-world-remco:test1 instead of  --image=trow.kube-public:31000/hello-world-remco:test1

Now its working. Sorry for the hassle.
greetz,
Remco

**Comment by Spazzy757** [comment]
No problem at all! Thanks for trying out trow!
