### ISSUE TITLE
Setup Smoke Test Script

### ISSUE THREAD

**Issue by Spazzy757** [ContainerSolutions/trow#147]
When changes are made to the Installation setup it would be good to have an automated script we could run in order to verify the changes. This could later be added to our release pipeline in order to automate the process before any major release. Current Installations that need to be tested are:
- Helm
- Kustomize

**Comment by amouat** [comment]
@Spazzy757 do you think we can close this following #180?

**Comment by Spazzy757** [comment]
Yeah definitely
