### ISSUE TITLE
list pushed images

### ISSUE THREAD

**Issue by pouledodue** [ContainerSolutions/trow#17]
Hi
Do you know how can list the pushed images?

**Comment by amouat** [comment]
Hi,

It is possible, but it's not supported by the Docker client afaik, so I'm afraid you need to use curl or similar. There are two commands, if you know the repository you want you can use the "list" operation, and if you want all repositories you can use the "catalog".

If you know the repository name and just want all the tags, try:

```
$ curl -k https://trow.kube-public:31000/v2/repo/tags/list
{"name":"repo","tags":["tag","tag2","tag3"]}
```

For the repositories try:

```
curl -k https://trow.kube-public:31000/v2/_catalog
{"repositories":["ng","test","repo","test/nginx","test/new"]}
```

I'll add some docs on this and close the issue once I've done that.

BTW these methods are based on the official spec, but there is a lot of debate about the catalog operation, so it might get dropped or defined differently in later versions of the spec. At the moment, don't expect it to work the same across different registry implementations.

**Comment by amouat** [comment]
Now documented here https://github.com/ContainerSolutions/trow/blob/master/docs/USER_GUIDE.md

Took me a while to remember Curl is unhappy unless you give it the root CA cert.
