### ISSUE TITLE
Helm chart: allow configuration with no user/pass

### ISSUE THREAD

**Issue by amouat** [ContainerSolutions/trow#171]
The Helm chart currently asks for a user and password, but it should also be possible to configure with no user/password set at all.

**Comment by alex-glv** [comment]
@amouat I can't reproduce this. Could you post exact steps?

**Comment by amouat** [comment]
You can install from the Helm chart without providing username/pass? It didn't look possible to me - maybe it's just a docs issue.

**Comment by Spazzy757** [comment]
@amouat Question on this, would you want the default for the helm chart to be no auth?

**Comment by amouat** [comment]
Yes, I *think* so. But either is fine as long as it's easy to change.
