### ISSUE TITLE
request canceled while waiting for connection 

### ISSUE THREAD

**Issue by foggy-glasses** [ContainerSolutions/trow#172]
Hello there!

I had previously deployed trow on a different cluster successfully and am attempting to do the same for a customer of our product. Everything seemed to go well until trow was deployed with the following config.

`        args:
          - "--no-tls"
          - "-n"
          - "clienttest.client.com.xx"
          - "-u"
          - "clientlogin-yy"
          - "--password-file"
          - "/etc/trow/pass"
`
I had also deployed nginx without TLS certs as I had mentioned no-tls in the args. However, I got the error that the cert mentioned in the ingress doesn't match with the hostname - i.e. ingress.local against clienttest.client.com.xx

Post this, I generated self signed certs with the hostname listed in the config and referenced it in the nginx-ingress config. When I attempt to login to the private registry using the command _docker login -u clientlogin-yy http://clienttest.client.com.xx_, I get the below error 

`Error response from daemon: Get http://clienttest.client.com.xx/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)`

I did a check in my ingress configuration again and ensured that I have set the directives ssl-redirect and force-ssl-redirect to "false". The logs from the nginx-controller pod do not show anything out of place either. When I try to curl to http://clientlogin-yy http://clienttest.client.com.xx/v2/_catalog. I got a 401 unauthorized error. 

Strangely, at the time of writing this last paragraph, even curl stopped working completely. I have decided to take this up with the respective parties, but I wanted to know how to ensure **trow** works on insecure mode and whether I need to make any more config changes to do so.

**Comment by amouat** [comment]
I can't recreate this problem. It should work - you're not doing anything unusual at the Trow level and I tried to recreate as much as I could (I haven't tried the nginx proxy).

The 401 error for  http://clientlogin-yy http://clienttest.client.com.xx/v2/_catalog is correct - you'd need to authenticate and pass the token in the header for this to work.

I think the problem is either with nginx or some networking issue. You don't need any further networking changes.

**Comment by foggy-glasses** [comment]
I agree.. I poked around the resolv.conf and finally found that proxy was set. So I unset the variables setting the proxy stuff and now I get a different error. I'll raise a different issue for that though. I'll close this for now.

Thanks @amouat for the reply!
