### ISSUE TITLE
Consider mkcert for quick install

### ISSUE THREAD

**Issue by blaggacao** [ContainerSolutions/trow#187]
https://github.com/FiloSottile/mkcert

A project specialized in solving some of the problems solved in `./quick-install`.

Breadcrumb trail: https://github.com/numtide/devshell/issues/27

**Comment by amouat** [comment]
I've seen mkcert, but do you think it helps us in this case? What would we gain by moving to mkcert?

**Comment by blaggacao** [comment]
I have to figure out how it plays along with #184 &mdash; especially the lb TLS part towards external client. My current understanding is that a generated CA (as a prerequisite artifact, yet automatically provisioned through mkcert) could make the quick-install more production-like (and maybe even save on those lines https://github.com/ContainerSolutions/trow/blob/f66fdac14c81f305563ca7c7ac949fe7695dfd69/quick-install/configure-host.sh#L115-L124)

**Comment by amouat** [comment]
I'm not sure `mkcert` really works for the quick-install flow. We already have a CA we can use - the k8s CA. Whichever solution we use we'd still need to copy the certs between machines and add them to the correct locations, so I don't see `mkcert` helping much. Also `mkcert` copies certs to the system store, which is ok, but arguably more intrusive.

**Comment by blaggacao** [comment]
The picture that is forming in my head is by using spire, achieving:
```markdown
# install/INSTALL.md
The default install will result in TLS being used between the registry client (Docker) and the
cluster ingress, but _not inside the cluster_. The next update to the Trow will use cluster
certificates to achieve full end-to-end TLS.
```

Then complement the ingress TLS with a mkcert workflow. It's still in flux in my mind, though.

IN such case, the ingress TLS CA could be shipped with this repo, ***for dev only***.

**Comment by amouat** [comment]
I'm not sure I follow. What I was planning to do was use the k8s CA internally. So the default install would have TLS termination at ingress, but then a new TLS connection to Trow. It shouldn't be difficult, I just never got around to it.

Dev only stuff is probably best shipped with the quick-install.

**Comment by blaggacao** [comment]
**Showcase:**

- &rarr; [ship with a root ca](https://github.com/ContainerSolutions/trow/pull/193/files#diff-04359bb04ecc08b0f19f634f869be71b73a5585e69c0f762403232b8ba6db226R88)
- &rarr; [enable &mdash; disable](https://github.com/ContainerSolutions/trow/pull/193/files#diff-4bb450507124b9bcd863a6d4a8fff3a75338d9a11c2ced8bb59b33f3f73637b0R12-R33) &mdash; `nix-shell`
- &rarr; [use it for the ingress](https://github.com/ContainerSolutions/trow/pull/193/files#diff-3cfa9fbd8ded31d751cf2934d96bbd41adde6e196122fa44dd70b4e5cc5f8a94)
- &rarr; [generate the secret through `kustomize`](https://github.com/ContainerSolutions/trow/pull/193/files#diff-827feadd710baf2e6812a1c9d4b5ddfe591d78a452ffec9ddc6cabeeb0046ca2R15-R20)

**Comment by amouat** [comment]
Thanks - the PR looks great, I just need to look through it and figure out how it works with everything and what it affects.

I don't really see mkcert as an issue that needs track, so I'm going to close this one.
