### ISSUE TITLE
Automatically approve and update certs on Trow restart

### ISSUE THREAD

**Issue by pouledodue** [ContainerSolutions/trow#19]
Trow was running well until I rebooted one K8s nodes.

Then `trow-init` container was failing on
```
Saved key to /certs/domain.key
certificatesigningrequest.certificates.k8s.io "trow.kube-public" deleted
certificatesigningrequest.certificates.k8s.io/trow.kube-public created

Waiting for CSR to be approved.

Please run:
$ kubectl certificate approve trow.kube-public
```

**Comment by amouat** [comment]
So when Trow came back up, it requested a new TLS certificate, which is probably necessary as it will have a new IP. It should be safe to rerun the install script, which won't recreate trow but will repeat the steps that approve and copy the cert to the appropriate locations.

I'm still considering the best solution to this. I've renamed the issue until I figure it out.

**Comment by amouat** [comment]
So, this is partly fixed on master. We're now distributing the CA cert rather than the trow cert, so clients don't need to be updated.

I'll test re-using the old cert to avoid the need to run "kubectl certificate approve", but this may fail due to the change in IP address.

**Comment by amouat** [comment]
On second thoughts, I need a way to update certs in case they are leaked or when they expire.
I think the correct solution is to find a way to automatically approve certificates, which probably means an operator.

If this happens again, just running "kubectl certificate approve trow.kube-public" should be enough, as all clients should have the CA cert and automatically trust the new cert.

I'm going to add a section on this to trouble-shooting and add an issue for auto-approving certificates, then close this issue.

**Comment by amouat** [comment]
In the end what I ended up doing was putting the key in a secret and reusing it, which does work. You shouldn't need to run `kubectl certificate approve`. I've also updated the user guide.

We still need a way to rotate certificates.
