### ISSUE TITLE
503 service unavailable

### ISSUE THREAD

**Issue by foggy-glasses** [ContainerSolutions/trow#192]
Hello there,

I had the strangest of errors crop up and I'm out of ideas as to why this would be happening. I'd appreciate any pointers on what is going on.

I have been using trow:0.2 for creating a private registry in on my clusters and last night I got the error `413 Entity Request is Too Large` and figured that my ingress (nginx kubernetes ingress) was missing the annotation for setting the _proxy-body-size_ to 0.

The next day after making the changes and applying them to the cluster, I tagged one of the images as usual and attempted to push them to my registry (hosted by trow) only to meet with a `503 Service Unavailable` error. I can see that docker daemon keeps trying to connect only to fail with the above mentioned error.

```
[user@server1 ~]$ sudo docker -D image push priv-registry.com/main/nginx-ingress-controller:0.33.0
The push refers to repository [priv-registry.com/main/nginx-ingress-controller]
c1a19c5d6c1c: Retrying in 1 second
ad2b0c034668: Retrying in 1 second
435bd169fb0e: Retrying in 1 second
cad00259deb3: Retrying in 1 second
fc61ccffc2c4: Retrying in 1 second
63fc60852e71: Waiting
7f16463c2512: Waiting
02a3a18a366c: Waiting
7cd38015fddc: Waiting
a46fe26caee6: Waiting
af89a9a077ee: Waiting
c4d79695750f: Waiting
a00053f4b396: Waiting
72d93ca3d27e: Waiting
3e207b409db3: Waiting
received unexpected HTTP status: 503 Service Unavailable
```

When I did a curl to priv-registry.com, I'm able to successfully get a response though. The registry is insecure and I've it to the daemon.json file under /etc/docker - My /etc/hosts file also contain the correct entries for resolving to priv-registry.com.

The docker daemon logs state that it received an unexpected HTTP response : 503 service unavailable - I tried changing some settings in the nginx ingress and using trow:0.3 instead of trow:0.2 - but there's no improvement at all. 

My cluster setup is behind a Fortinet LB that is configured separately and my ingress service runs as a NodePort service with the nodeports mapped to the LB correctly in Fortinet.

**Comment by amouat** [comment]
Is there anything in the Trow log? One possibility is it's failing the readiness check because of file permission problems. If you just run `kubectl get deployment trow`, that should tell you if there's anything wrong there.

If that's not the problem, check the Trow log. I suspect the requests aren't even reaching Trow, in which case it has to be something to do with the Service or the Load Balancer. I would then start testing each level in turn with `curl` or similar and double checking the config.

**Comment by amouat** [comment]
Based on the information provided, I'm fairly sure this is a problem with the configuration of the ingress or service.

For that reason, I'm going to close the issue for the moment, but please open it again if you can't get it work & have more information for me (e.g. logs, ideally using the image from the other issue).
