### ISSUE TITLE
image persistence

### ISSUE THREAD

**Issue by pouledodue** [ContainerSolutions/trow#20]
After rebooting a node I get
```
$ kubectl get event --sort-by .lastTimestamp -A --field-selector='type!=Normal'

Failed to pull image "trow.kube-public:31000/test/woot:latest": 
rpc error: 
code = Unknown 
desc = Error response from daemon: 
error parsing HTTP 404 response body:
 json: cannot unmarshal string into 
Go value of type struct { Errors []errcode.Error }: "\"404 page not found\""
```

when I issue this command 
```
curl -k https://trow.kube-public:31000/v2/_catalog
```
I get an empty 
```
{"repositories":[]}
```

How can I make sure images pushed are persisted between node reboots?

**Comment by amouat** [comment]
Yes, I need to document this as well. 

Data is currently stored in an `emptyDir` volume by default. It seems this is wiped on pod restarts, so it needs to be changed to whatever is appropriate for a persistent volume your cluster (https://kubernetes.io/docs/concepts/storage/volumes/#types-of-volumes).

There is an example of doing this for GKE in install/trow-gke.yaml. If you're on GKE, just copy trow-gke.yaml over trow.yaml.

I'll leave this open until I've added docs on this.

**Comment by amouat** [comment]
Now documented in [User Guide](https://github.com/ContainerSolutions/trow/blob/master/docs/USER_GUIDE.md) so I'll close this issue.

Thanks for opening the issue!
