### ISSUE TITLE
Add Certificate Rotation

### ISSUE THREAD

**Issue by amouat** [ContainerSolutions/trow#21]
Need some way to automatically update certificates

**Comment by eeiscmy** [comment]
Hi,
I am hitting the below issue on docker push. Is it related to this?
 #docker push trow.kube-public:31000/nginx:1.0.0
The push refers to a repository [trow.kube-public:31000/nginx]
Get https://trow.kube-public:31000/v1/_ping: x509: certificate has expired or is not yet valid
Thanks,
Seamus

**Comment by amouat** [comment]
Are you using Docker for Mac? Try restarting Docker. But no, it's not related.

**Comment by eeiscmy** [comment]
Hi,
I got it sorted. The date on my client VirtualBox  VM (CentOS) was a day behind for some reason. I corrected the date and it is working now.
Thanks for the quick response.
Seamus.

**Comment by amouat** [comment]
No problem, glad you got it working.

**Comment by amouat** [comment]
I'm closing this issue as production certificates should be provided by something like lets encrypt ingress, which will take care of rotation. It may become relevant again for internal TLS within the Trow cluster, but we can open a new issue then if need be.

At the moment the issue is causing confusion.
