### ISSUE TITLE
Openshift Kube Cluster and Trow

### ISSUE THREAD

**Issue by fatdrag0n** [ContainerSolutions/trow#219]
I have a openshift kube cluster running and ran into trow usefulness!

I am getting ready to run install.sh
I am reviewing the script.

Should I rename any domain or name specific to my environment or server in the yaml files in quick-install folders?

Any thing I should watch out for?
Should I run the script as root or my own username?

Thanks

**Comment by amouat** [comment]
The quick-install is for testing and development clusters. It will set-up a self-signed certificate and routing for trow.kube-public:31000 by default.

In your case you really want to use the [standard install](https://github.com/ContainerSolutions/trow/blob/master/install/INSTALL.md), either using Helm chart or Kustomize. This uses a certificate for your domain and via Kubernetes ingress. Exactly how this works depends on how your cluster is set-up (e.g. certmanager).

I'll close this issue for the moment, but please open a new one if you hit any problems.

Thanks for taking a look at Trow!
