### ISSUE TITLE
Private registries caching

### ISSUE THREAD

**Issue by Guillermogsjc** [ContainerSolutions/trow#233]
As trow can be used as a proxy against a container repository, and it is efficiently used with DockerHub with `--proxy-docker-hub`, could this feature be extended to provide proxy cache against private repositories (ECR, GCR or ACR) ?

The use case is very strong, because inside Kubernetes the most pulled repositories usually are private.

**Comment by amouat** [comment]
Yeah, absolutely this is a goal. It shouldn't be too much more work above the DockerHub proxying, but it does take some effort to get the interface right.

**Comment by amouat** [comment]
Not really. I've been working on some refactorings, and then this will be the next goal. I'm hopeful that I will have time to do this after Easter, but it won't be before I'm afraid.

Thanks for commenting though, it's good to know what people are looking for.

**Comment by amouat** [comment]
@will-ds would you like to e-mail me? I'd be interested in knowing more about your use case and potentially using it to drive the design.

**Comment by jpuskar** [comment]
FWIW, I was just about to install Trow when I saw this issue. The use-case would be: decoupling our Artifactory private docker registry from the kubernetes clusters.
