### ISSUE TITLE
Can't pull docker:dind through dockerhub proxy

### ISSUE THREAD

**Issue by awoimbee** [ContainerSolutions/trow#264]
**Describe the bug**
I can't pull docker:kind through the docker hub proxy.

**To Reproduce**

```bash
# This works
kubectl run test -it --rm --image docker:dind
# This doesn't
kubectl run test -it --rm --image ${KIND_URI}/f/docker/docker:dind
```

**Expected behavior**
I expect the same behavior from both commands (a pod running `docker:dind` is spawned).

**Output/Logs**
kubectl describe:
```
  Normal   Scheduled  <invalid>  default-scheduler  Successfully assigned actions-runners/test to xxxxxxxxxxxxx
  Normal   Pulling    <invalid>  kubelet            Pulling image "xxxxxxxxx/f/docker/docker:dind"
  Warning  Failed     <invalid>  kubelet            Failed to pull image "xxxxxxxxx/f/docker/docker:dind": rpc error: code = Unknown desc = Error response from daemon: error parsing HTTP 404 response body: json: cannot unmarshal string into Go value of type struct { Errors []errcode.Error }: "\"404 page not found\""
  Warning  Failed     <invalid>  kubelet            Error: ErrImagePull
  Normal   BackOff    <invalid>  kubelet            Back-off pulling image "xxxxxxxxx/f/docker/docker:dind"
  Warning  Failed     <invalid>  kubelet            Error: ImagePullBackOff
```

Trow:
```logs
[2021-07-22T13:13:24Z WARN  trow_server::server] Internal error with manifest ErrorMessage { msg: "Failed to find artifact with digest sha256:7f8d570be2274d0bfa2a8df30021696ca2af3e7a44553d24aa5f58314e32590b" }
[2021-07-22T13:13:24Z WARN  rocket::response::responder] Response was `None`.
[2021-07-22T13:13:24Z WARN  rocket::rocket] Responding with 404 Not Found catcher.
[2021-07-22T13:13:37Z WARN  trow_server::server] Internal error with manifest ErrorMessage { msg: "Failed to find artifact with digest sha256:7f8d570be2274d0bfa2a8df30021696ca2af3e7a44553d24aa5f58314e32590b" }
[2021-07-22T13:13:37Z WARN  rocket::response::responder] Response was `None`.
[2021-07-22T13:13:37Z WARN  rocket::rocket] Responding with 404 Not Found catcher.
```
Note: I have a lot of these warnings in the Trow log.

**Trow Info**
 - Install method: Helm 0.3.0 (customized for dockerhub proxy)
 - Version/Image Name: containersol/trow:0.3.2

**Kubernetes**
 - Kubernetes distro/host: EKS
 - Kubernetes version: 1.19
 
 Note:
 Seems like it's related to #173

**Comment by amouat** [comment]
Thanks, I'll try to take a look today

**Comment by amouat** [comment]
It looks like it's a bug that was fixed by this PR https://github.com/ContainerSolutions/trow/pull/255. The real bug is that the Helm chart needs to be updated to point to the fixed image. This should really happen automatically, but is currently done manually and the steps are undocumented, so I'm struggling to figure out what's meant to happen.

It should be updated later today - I'll let you know when I have something for you to test.

**Comment by amouat** [comment]
@awoimbee could you test with version 0.3.3? Just updating the image should be enough.

**Comment by awoimbee** [comment]
Thanks for updating both the container and the chart, everything now works and the logs in the issue disappeared 🌟

**Comment by amouat** [comment]
Great, thanks for getting back to me.
