### ISSUE TITLE
Docker push times out

### ISSUE THREAD

**Issue by akaliwod** [ContainerSolutions/trow#278]
**Describe the bug**
I have followed quick-install guide steps to start trow on my kubernetes cluster. Installation completed without any major problems and I wanted to push the first container to image registry. docker push fails.

**Expected behavior**
docker push should complete

**Output/Logs**
$ kubectl logs trow-deploy-5f6fb657dc-pt2cc -n trow-registry
Starting Trow 0.3.0 on 0.0.0.0:8443

**Validation callback configuration

  By default all remote images are denied, and all local images present in the repository are allowed

  These host names will considered local (refer to this registry): ["trow:31000", "trow.trow-registry:31000"]
  Images with these prefixes are explicitly allowed: ["k8s.gcr.io/", "docker.io/containersol/trow"]
  Images with these names are explicitly allowed: []
  Local images with these prefixes are explicitly denied: []
  Local images with these names are explicitly denied: []

Trow is up and running!

$ tail -1 /etc/hosts
127.0.0.1 trow.trow-registry

$ sudo docker push trow.trow-registry:31000/nginx:alpine
The push refers to repository [trow.trow-registry:31000/nginx]
40403bebe4fd: Retrying in 1 second
b4b4e85910ea: Retrying in 1 second
311d8db33235: Retrying in 1 second
20d0effdf3a2: Retrying in 1 second
e6d3cea19fef: Retrying in 1 second
e2eb06d8af82: Waiting
received unexpected HTTP status: 503 Service Unavailable

**Trow Info**
 - Install method: quick install
 - Version/Image Name 0.3.0
 
**Kubernetes**
 - Kubernetes distro/host (Cisco IKS)
 - Kubernetes version (1.19.5)

**Comment by akaliwod** [comment]
Thanks for help. I will try once more with standard install.

IKS is running on 3 VMs (esxi). 1CP + 2Workers. I was running all CLI commands from the CP node.

iksadmin@milan-kali-controlpl-e35067d1aa:~$ kubectl get nodes -o wide
NAME                              STATUS   ROLES    AGE     VERSION    INTERNAL-IP   EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION       CONTAINER-RUNTIME
milan-kali-controlpl-e35067d1aa   Ready    master   3d20h   v1.19.15   10.58.29.71   10.58.29.71   Ubuntu 18.04.5 LTS   4.15.0-156-generic   docker://19.3.13
milan-kali-workers-12e76ffb2a     Ready    <none>   3d20h   v1.19.15   10.58.29.69   10.58.29.69   Ubuntu 18.04.5 LTS   4.15.0-156-generic   docker://19.3.13
milan-kali-workers-2eacf690b1     Ready    <none>   3d20h   v1.19.15   10.58.29.70   10.58.29.70   Ubuntu 18.04.5 LTS   4.15.0-156-generic   docker://19.3.13

IKS as of now is not pre-installed with image repository (as of now) so I wanted to use Trow for that purpose.

I could not find out where I get the 503 from. 'curl' test on trow.trow-registry:31000 responded with empty repository so I assumed that the requests reach trow. however, when doing docker push command, I could not find anywhere the reason for problem... will re-install and keep on digging. 

thanks

**Comment by amouat** [comment]
I'm sorry, I missed this reply. Apologies if you've moved on from this already.

I did just fix a bug with an outdated image being used in the quick install, which might help things.

I think the best thing to do is up the logging level and see if you get anything else from the Trow logs. To do this we need to edit the YAML. In the quickstart this means changing the line:

```
  args: ["-n", "trow:31000 trow.{{namespace}}:31000", "-c", "/certs/domain.crt"]
```

to:

```
  args: ["--log-level", "DEBUG", "-n", "trow:31000 trow.{{namespace}}:31000", "-c", "/certs/domain.crt"]
```

If there's still no output on `docker push` we can fairly confident that the requests aren't reaching Trow at all and something is broken at a routing layer. It's odd that `curl` would work but not `docker push` though. Could you also provide the output from the curl command.

**Comment by amouat** [comment]
I'm going to close this for the moment as I can't do anything without more info. Please re-open if you come back to this. Apologies for the delay in replying.
