### ISSUE TITLE
Please cut a 0.3.4 helm release to resolve networking.k8s.io/v1beta1 deprecation

### ISSUE THREAD

**Issue by salimepoint** [ContainerSolutions/trow#282]
**Describe the bug**
The 0.3.3 helm release includes the `ingress.yaml` template that references `networking.k8s.io/v1beta1` (which has been deprecated). `main` has the fixed version of `ingress.yaml` in it but it has not been included in an accessible `https://trow.io` release.

**To Reproduce**
Attempt to install the helm package - it should fail with:

```
Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "Ingress" in version "networking.k8s.io/v1beta1"
```

**Expected behavior**
helm chart installs successfully.

**Output/Logs**
as above

**Trow Info**
 - Install method (Helm)
 - Version/Image Name (e.g. `0.3.3`) 

**Kubernetes**
 - Kubernetes distro/host (k3s)
 - Kubernetes version (1.22)
 - Container Runtime (n/a)

Hopefully `main` is in a releasable state and this is a simple one :-).  Obviously if there's a way I can use the repo itself as the install source for helm that would also solve the problem but my googling hasn't shown me a way I can do that (other than cloning and installing it manually - which makes including trow as a dependency difficult)

**Comment by amouat** [comment]
Sure, let me take I look.

**Comment by amouat** [comment]
Apologies for the delay - I didn't quite get this finished before the holidays.

I just merged an update. Hopefully this should work fine, but please let me know if there are any problems (feel free to reopen this issue).

Closing for the moment.
