### ISSUE TITLE
Race conditions on the file system

### ISSUE THREAD

**Issue by awoimbee** [ContainerSolutions/trow#309]
**Describe the bug**
Concurrently pulling images that share layers will lead to corrupted data. The major culprit is https://github.com/ContainerSolutions/trow/blob/b7de218b810e7c03bbcb81a1968af00c236de2d3/lib/server/src/server.rs#L424

There are many calls to `File::create(Path)` without any check, these calls truncates existing files and will corrupt them if multiple tasks are writing concurrently.

**To Reproduce**
No reproduction, this is more an epic than a standard issue.

**Expected behavior**
No filesystem corruption due to race conditions.

**Comment by amouat** [comment]
Crap. Thanks for finding this.

**Comment by amouat** [comment]
I just had a quick look - note the use of UUIDs, so I'm not sure this is a problem in practice?
