### ISSUE TITLE
Connection Timeout

### ISSUE THREAD

**Issue by RAbraham** [ContainerSolutions/trow#31]
Hi,

We are following the instructions according to the video: https://asciinema.org/a/48HK88yR4rJw0QuHt2VdkuVZn

We get a connection timeout issue:
```
sudo docker push trow.kube-public:31000/test/nginx:alpine
The push refers to repository [trow.kube-public:31000/test/nginx]
Get https://trow.kube-public:31000/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```

On using `describe`, we see:
```
 Warning  FailedCreate  15m (x3 over 15m)     replicaset-controller  Error creating: Internal error occurred: failed calling webhook "validator.trow.io": Post https://trow.kube-public.svc:443/validate-image?timeout=30s: service "trow" not found
```
Service `trow` is running in `kube-public`, not sure why it's not finding it.

Appreciate any help.

**Comment by amouat** [comment]
Interesting.

Can you provide some more details of your environment? Are you running on GKE, minikube etc? Which version of k8s are you using?

At first glance it looks like either a routing or firewall issue; can you make sure port 31000 is open and accessible?

**Comment by RAbraham** [comment]
Cool, we'll try firewalls again. When you say validation, do you mean using authentication?
Also, were there pods to be created. Because we didn't see any. A service was only created.

**Comment by RAbraham** [comment]
We are running on GKE.

**Comment by amouat** [comment]
As you're running on GKE I'm pretty sure it's just a firewall issue. If you search in the console for "firewall rules", you should be able to create a new rule that allows incoming traffic from all IPs to port 31000. I'll see if I can come up with a gcloud command to configure this that I can add to the docs.

**Comment by amouat** [comment]
I've added this to the install instructions and the script. I should probably re-record the video at some point to include this step.

Please let me know if opening the firewall worked for you and I'll close this issue.

**Comment by amouat** [comment]
I've not heard anything, so closing this issue.

Thanks for the report.

**Comment by RAbraham** [comment]
I apologize for not replying sooner. I moved on and got caught up with deadlines. Sorry about that.

**Comment by amouat** [comment]
No problem, let me know if you still have problems.
