### ISSUE TITLE
Request to release v0.3.5

### ISSUE THREAD

**Issue by MukeshS-hexaware** [ContainerSolutions/trow#317]
I am currently using the Helm chart version of Trow, and when I deploy Trow to AKS and try to pull images from Trow, I'm facing this error:

```
Failed to pull image "trow/test:latest": rpc error: code = FailedPrecondition desc = failed to pull and unpack image "trow/test:latest": failed commit on ref "layer-sha256:60324950a964e825b7fa78043fbe2330be484170e14f6ae6b7baeb4950f4bc9b": "layer-sha256:60324950a964e825b7fa78043fbe2330be484170e14f6ae6b7baeb4950f4bc9b" failed size validation: 318653 != 318654: failed precondition
```

I'm thinking this has been already fixed in e9e2a83de4da77962aef0728ec2e34a6e678fc98, which has not been included in any release yet.

Please publish a new release with this commit included.

**Comment by amouat** [comment]
Sure, I'll take a look later.

**Comment by MukeshS-hexaware** [comment]
Hi, any updates on this?

**Comment by amouat** [comment]
Hey, this should be done now. Apologies for the delay, I was having some trouble with releases and new machines.

Let me know if there are any issues!
