### ISSUE TITLE
something possibly broke layer uploading

### ISSUE THREAD

**Issue by sjpotter** [ContainerSolutions/trow#37]
uploading with skopeo to trow and seeing this failure.  could also be smething that changed in skoepeo?

```
trow_server::server[WARN] Failure when saving layer: ErrorMessage { msg: "Upload did not match given digest. Was given sha256:d76b71c9e6e74bb0f3b89cbaef87cbc6eddbc15896de3e655895a31d2ba97a7f but got d76b71c9e6e74bb0f3b89cbaef87cbc6eddbc15896de3e655895a31d2ba97a7f" }
```

only thing I can think of is the sha256 prefix?

**Comment by amouat** [comment]
Oops, I just added that code. Clearly I made a mistake somewhere...

Thanks, I'll take a look at it today.

**Comment by amouat** [comment]
Should be fixed now. I need to add better tests for master as this should never have got through.

Thanks.
