### ISSUE TITLE
Document certs needed for development

### ISSUE THREAD

**Issue by amouat** [ContainerSolutions/trow#49]
To run `cargo test`, the developer will need to first create a certificate for Trow to use. We should document this better.

**Comment by blaggacao** [comment]
#193 might help under `./dev/ca` or `./dev/tls`

**Comment by amouat** [comment]
Closing via https://github.com/ContainerSolutions/trow/commit/78972e683fff90e9686e3d685ccb1da7c9208d6e (I did mention hostctl and mkcert).
