### ISSUE TITLE
Doing uploads in POST waits for invalid payload to stream

### ISSUE THREAD

**Issue by mcwienczek** [ContainerSolutions/trow#55]
Doing uploads in POST streams all the data of an invalid payload to /dev/null. This can still strain the resources of trow instance. We should be breaking the connection once we already see that the payload is invalid.

See this line for more info: https://github.com/ContainerSolutions/trow/pull/54/files#diff-e12f07ef6d281c675e309912e464c925R494

**Comment by mcwienczek** [comment]
Fixed with #54

**Comment by amouat** [comment]
Are you sure this should be closed? Wasn't it about this line? https://github.com/ContainerSolutions/trow/blob/master/src/routes.rs#L538

To close the connection, we don't need to do anything, Rocket will pick up that the data wasn't touched and drop the connection. I'm just not 100% sure what is the right thing to do. Note that this also occurs in the patch upload code.

**Comment by mcwienczek** [comment]
My mistake. Sorry.

**Comment by amouat** [comment]
No worries, I made a quick PR. If you have time, take a look and see if it makes sense to you.

All I really did was changed the logging and remove the stream line!
