### ISSUE TITLE
Tutorial Video

### ISSUE THREAD

**Issue by sbussard** [ContainerSolutions/trow#58]
It would be really nice to have a tutorial video so I can see what it is supposed to look like when it works.
I ran into problems following the quick start instructions (with certificates on various levels).

Thanks

**Comment by sbussard** [comment]
I meant on youtube... but I see there is one here. Closing.

**Comment by amouat** [comment]
Thanks Stephen.

I need to update the videos, so I might put one up on youtube as well. It's a good idea.
