### ISSUE TITLE
Support foreign blobs in manifests

### ISSUE THREAD

**Issue by gimlichael** [ContainerSolutions/trow#64]
I have followed your guide - but needed to do a lot of tweaks for my Kubernetes setup.
That said, it is working now .. at least until i try to push an image to the registry.

I keep getting this error from docker push: manifest invalid
If i look in the mounted volume, i can see that `blobs `and `scratch `receives data, but `manifests `remains empty.

I am lost for ideas to pursue now - please help me out.

My setup:

Kubernetes 1.17.3
Trow: more or less the recommended installation guide (again, with plenty of tweaks)
Volume: NFS share using https://github.com/kubernetes-incubator/external-storage/tree/master/nfs-client

However, to reduce trial/error, i setup a static mount using pv and pvc.

It fails in both scenarious, though .. :-(

Let me know how i can provide more information.

Thanks.

**Comment by amouat** [comment]
Hi,

Do you know which version of Trow you're running? What's the image name and what does `trow --version` report?

Does it happen with all images or just one? Could you provide me with access to an image that doesn't work?

At the moment my only advice is to try updating the version of Trow if it's at all possible it could be old.

**Comment by gimlichael** [comment]
> Hi,
> 
> Do you know which version of Trow you're running? What's the image name and what does `trow --version` report?
> 
> Does it happen with all images or just one? Could you provide me with access to an image that doesn't work?
> 
> At the moment my only advice is to try updating the version of Trow if it's at all possible it could be old.

I am a little confused; I used the https://github.com/ContainerSolutions/trow/blob/master/install/INSTALL.md in order to install Trow. The image that does not work, works fine on ACR. As a reference, I am trying to setup JFrog Container Registry as well for me to pinpoint what the error could be (probably an error by me).

trow --version is not a command i am aware of.

**Comment by gimlichael** [comment]
Just a heads up: I was able to make it work with JFrog Container Registry; that said, i would prefer trow as it by far more lightweight. Keep up the good work - and let me know if you need more information.

In regards to the image; it is a windows image (so its rather large - damn Microsoft) for my legacy applications written in .NET Framework and hosted on IIS. 

All new application will be made on Linux and .NET Core.

Cheers.

**Comment by amouat** [comment]
Thanks. 0.2 should be fine. Can you give me the name of the base image? I could try testing with that. Is it just that image that didn't work - can you try pushing e.g. alpine:latest to trow?

**Comment by gimlichael** [comment]
Yeah, sure .. everything works fine until docker is finalizing the push, eg. everything is pushed as expected to the server, but the manifest part is never pushed/stored.

This is the base image: mcr.microsoft.com/dotnet/framework/aspnet:3.5-windowsservercore-1909

**Comment by amouat** [comment]
Yeah, it looks like it's to do with the base image. In OCI distribution manifests, you can have "foreign" blobs which can't be pushed to registries and must always be downloaded from the original source (microsoft in this case). At the moment Trow doesn't support foreign blobs. 

To be honest, I'm not a huge fan of foreign blobs, as they break a bunch of stuff for questionable benefit but I'll have a go at supporting at them this week.

I'll change the title to reflect the issue. 

You can read a bit more here https://docs.docker.com/registry/spec/manifest-v2-2/ and you can probably find discussion on various issue trackers.

**Comment by amouat** [comment]
Ok, so I think I've fixed this on master. 

The images on Docker Hub are getting rebuilt at the minute. Could you change to using `trow:default` or `latest` and see if that fixes things?
