### ISSUE TITLE
the current version is not accessible from the host

### ISSUE THREAD

**Issue by takaczapka** [ContainerSolutions/trow#72]
Although all k8s configs look ok, trow pod log is confusing - server port listening on 51000?

Regardless the correct entry in /etc/hosts on the host machine, the repo is not accessible/available.

```$ k logs -n kube-public trow-deploy-76fdd7784b-mbxmz
Starting Trow 0.3.0 on 0.0.0.0:8443

**Validation callback configuration

  By default all remote images are denied, and all local images present in the repository are allowed

  These host names will considered local (refer to this registry): ["trow:31000", "trow.kube-public:31000"]
  Images with these prefixes are explicitly allowed: ["k8s.gcr.io/", "docker.io/containersol/trow"]
  Images with these names are explicitly allowed: []
  Local images with these prefixes are explicitly denied: []
  Local images with these names are explicitly denied: []

trow_server[WARN] Server listening on 127.0.0.1:51000
Trow is up and running!```

**Comment by amouat** [comment]
Ignore the "Server listening" line. Basically the architecture of Trow means it has a front end (listening on 8443) and a backend which the front-end talks to via port 51000. This is an internal details you don't need to worry about. I'll remove the log-line if I can as it is confusing.

I need a few more details to debug this. What is the actual error (timeout?) and what platform are you on? Have you made sure port 31000 is open on the firewall?

**Comment by amouat** [comment]
At the moment, I think this was probably caused by a firewall between the client and Trow, probably the default one in GCP or AWS. Without more information, I can't debug it.

The log line does need fixed however. Once I've fixed that, I'll close this issue unless I get more information.

**Comment by takaczapka** [comment]
I run it locally, went through regular installation steps. Never managed to access it from localhost though, hence the post. 

Sorry, I cannot provide any more info - I don't need it anymore, as the spike I was working on is finished and I've managed to achieve everything by running out of the box docker registry locally. 

Thanks,
Maciej
