### ISSUE TITLE
Helm Installation

### ISSUE THREAD

**Issue by amouat** [ContainerSolutions/trow#73]
The main installation instructions are based on Kustomize, but it seems most people want to use Helm. We should support Helm as well.

**Comment by plod** [comment]
Happy to have a look at this, not used kustomize for over a year, but deep in the weeds with helm at the moment, and was looking for a helm chart.

**Comment by amouat** [comment]
Sure, that would be hugely appreciated! Please leave a comment or e-mail me if you have any questions.

**Comment by amouat** [comment]
Hey, thanks a lot for the offer! @Spazzy757 reached out earlier to say he was working on it and I forgot to update this ticket. Apologies for not updating this ticket.

Would you be willing to take a look at the PR @plod ?

**Comment by plod** [comment]
Yes absolutely!

**Comment by amouat** [comment]
Thanks @plod. @Spazzy757 submitted PR #122, which I think is pretty much what we need, it's just lacking docs atm.

I know very little about Helm charts though, so please take a look and let us know if you think it should be changed at all!
