### ISSUE TITLE
Public container image

### ISSUE THREAD

**Issue by jdolitsky** [ContainerSolutions/trow#90]
Please publish a public container image on Quay/Docker Hub (or other) in order to use for OCI conformance purposes

**Comment by amouat** [comment]
The one tracking master is `containersol/trow:default` on the Docker Hub. Do you a need different image with the tests included?

**Comment by jdolitsky** [comment]
Nope thats fine, just missed it in the docs. Thank you!

**Comment by amouat** [comment]
BTW, I just set up GitHub actions to build Docker Images, so going forward you will be able to find dated builds in packages: https://github.com/ContainerSolutions/trow/packages/195013

I might also push using the commit hash or similar.
