### ISSUE TITLE
Connection Refused while trying to push image to registry

### ISSUE THREAD

**Issue by mewais** [ContainerSolutions/trow#98]
Hi, I am a bit new to Kubernetes in general, so apologies in advance for anything I may have missed or misunderstood.

I was following the [standard install guide](https://github.com/ContainerSolutions/trow/blob/master/install/INSTALL.md) for installing trow on my own local cluster. As far as I can tell, Trow is deployed and works fine.

running `kubectl get pods -n trow` gives me this:
```
NAME         READY   STATUS    RESTARTS   AGE
trow-set-0   1/1     Running   0          148m
```

`kubectl get svc -n trow` gives me:
```
NAME       TYPE       CLUSTER-IP     EXTERNAL-IP   PORT(S)          AGE
trow-svc   NodePort   10.99.19.126   <none>        8000:30573/TCP   148m
```

`kubectl get ingress -n trow` also gives me:
```
NAME           CLASS    HOSTS        ADDRESS   PORTS     AGE
trow-ingress   <none>   trow.local             80, 443   150m
```

and finally `kubectl logs -n trow trow-set-0` yields:
```
Running /trow --no-tls -n trow.local -u mewais --password-file /etc/trow/pass
Starting Trow 0.2.0 on 0.0.0.0:8000

**Validation callback configuration

  By default all remote images are denied, and all local images present in the repository are allowed

  These host names will considered local (refer to this registry): ["trow.local"]
  Images with these prefixes are explicitly allowed: ["k8s.gcr.io/", "docker.io/containersol/trow"]
  Images with these names are explicitly allowed: []
  Local images with these prefixes are explicitly denied: []
  Local images with these names are explicitly denied: []

trow_server[WARN] Server listening on 127.0.0.1:51000
Trow is up and running!
```

Now, I'm trying to actually push an image to trow, so I built a docker image, and then I tried `sudo docker push trow.local:31000/name:tag` but it always gives me the error:
```
The push refers to repository [trow.local:31000/event-downloader]
Get https://trow.local:31000/v2/: dial tcp 10.10.1.1:31000: connect: connection refused
```

This is being built on a simple, local, kubernetes cluster consisting of 3 master nodes, 3 worker nodes with rook-ceph for storage, and 2 worker nodes with no storage, no firewalls, the IP address in the last error message is for the first master node.
Also, I had used the quick install before, it worked well, and I was able to push images to the registry just fine. It had also mapped `trow.kube-public` to the same IP address.

I'm not sure what may be the problem, any help would be appreciated.

**Comment by amouat** [comment]
Part of the quick installation script is to set `trow.kube-public` to point to the IP address of the cluster in `/etc/hosts`. In the standard install, the routing is expected to be done via a domain name pointed at the cluster.

What you've done will work, but you need to update `/etc/hosts/` to point at the IP address of one of the nodes of your cluster and use the port that was assigned. 

IIRC correctly `kubectl get nodes -o wide` will report the IP addresses of your nodes. Set the value in `/etc/hosts` to that. Then either update the service YAML to use port 31000 as the NodePort or change your push command to use the port 30573 that is assigned currently i.e:

`docker push trow.local:30573/name:tag`

You will then hit the issue that Docker will refuse to trust the repository as it isn't using TLS. Here you have two choices - you can turn TLS on and copy the cert into your Docker config as per the quick install, or set-up Docker to allow an insecure registry at that address (https://docs.docker.com/registry/insecure/). If you use the insecure registry option, you will need to turn off authentication.

The way you have configured things currently is *strongly* discouraged. You really should be using TLS, either from the client to the kubernetes ingress, or from the client to Trow (ideally both, but the install isn't set-up for that currently). It doesn't matter for local testing, but if anyone else is going to use this or it is going to exposed over the internet, it *must* be fixed.

Thanks for trying Trow & please let me know how you get on!

**Comment by mewais** [comment]
Thank you for your response, I actually had the `trow.local` in my `/etc/hosts`. That's how in the last error message you can see that it was able to translate it to `10.10.1.1`. My problem actually was the port number. Once I changed it from 31000 to 30573 and reran the command `sudo docker push trow.local:30573/name:tag` I got this output:
```
The push refers to repository [trow.local:30573/name]
Get https://trow.local:30573/v2/: EOF
```
I don't understand what's the problem now. Can't find anything similar in the issues here. But it looks like progress :) Is this related to TLS?

**Comment by mewais** [comment]
Right now, I'm using a bunch of old laptops and PCs to build this cluster, this is basically a learning and testing phase. Once this is complete, the end goal is to deploy it to an actual production cluster where it will host applications for a team. So definitely, at some point, I will be needing to set up TLS. But as I said, since I am a bit new to Kubernetes in general, I was just trying to take it bit by bit.

I think right now what I should do is look at the quick_install script and follow what it does to create a certificate. Thanks a lot for your help.

**Comment by amouat** [comment]
Nice. 

When you look at the script, note that some of what happens is passed off to a cron job, which you should be able to find the script for.

I think something like inlets.dev might give you a good balance though, it will be closer to how things work in a production environment.

**Comment by mewais** [comment]
Great, thanks a lot for your help :)
